### PR TITLE
add Gradle Wrapper validation

### PR DESCRIPTION
**Pull request by sullis**
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action
﻿

### CODE REVIEW

**Comment by sullis** [comment]
Screen Shot 2020-08-23 at 12 34 58 PM

**Review by koral-- — CHANGES_REQUESTED** [review]
We have sha cheksum declared in Gradle wrapper properties: https://github.com/mockito/shipkit/blob/master/gradle/wrapper/gradle-wrapper.properties#L7

So every invocation when wrapper is not yet downloaded will cause validation to be performed automatically. No matter if running on CI or not.
As you can see on Travis CI log it is also downloaded there.

Apart from that we're using Travis, not Github actions, what is the purpose of performing additional validation?

**Comment by szpak** [comment]
> Apart from that we're using Travis, not Github actions, what is the purpose of performing additional validation?

@koral-- That validation can be useful to confirm that the wrapper upgrade proposed in a PR is not the rogue one. For example, that check could [detect](https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action) malicious `gradle-wrapper.jar` which always downloads Gradle from arbitrary location, ignoring defined SHA hash.

However, as you noted, using Travis instead of GitHub Actions is a very good point which complicates that PR in ShipKit ;).

**Comment by sullis** [comment]
> > Apart from that we're using Travis, not Github actions, what is the purpose of performing additional validation?
> 
> @koral-- That validation can be useful to confirm that the wrapper upgrade proposed in a PR is not the rogue one. For example, that check could [detect](https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action) malicious `gradle-wrapper.jar` which always downloads Gradle from arbitrary location, ignoring defined SHA hash.
> 

Gradle's GitHub Action validates the Gradle wrapper jar against a known list of valid checksums.

The `gradle-wrapper.properties` file in the ShipKit repo could contain a rogue checksum.

**Comment by koral--** [comment]
OK now I get it.
So it seems that we can have this GH action validation in parallel with Travis. GitHub allows multiple PR checks.
What do you think guys?

**Comment by mstachniuk** [comment]
For me it's ok to validate gradle-wrapper using GH Actions.

**Comment by sullis** [comment]
ping @mstachniuk @koral--

**Review by koral-- — APPROVED** [review]

**Pull request merged**
