### PR TITLE
Spec for discussing future of Shipkit

### PR DESCRIPTION
**Pull request by mockitoguy**
@mockito/shipkit-developers, any thoughts?

### CODE REVIEW

**Comment by epeee** [comment]
:+1:, thx!

**Comment by mockitoguy** [comment]
I'll keep it open for 1-2 weeks to collect more feedback.

Thanks for review!

**Comment by nallar** [comment]
> adoption is small (too opinionated? / too complicated?).
a little of that, ~~but also you're missing out on expensive consultants pushing people to move to it as a way to generate work~~

Not that it means much, but shipkit's saved a lot of time here and very happy that it exists.

**Comment by mockitoguy** [comment]
@nallar, thank you for feedback!

**Pull request merged**
