### PR TITLE
Explicit distro that still supports oraclejdk8

### PR DESCRIPTION
**Pull request by pzygielo**
Similar to https://github.com/mockito/mockito/pull/1750

### CODE REVIEW

**Comment by pzygielo** [comment]
I suppose things such as https://travis-ci.org/mockito/shipkit/builds/564187877#L444 causes my repeated failures.

So just for evidence 
- last success https://travis-ci.org/mockito/shipkit/builds/526072486#L9 - trusty
- first error https://travis-ci.org/mockito/shipkit/builds/563376544#L9 - xenial

Feel free to act according to your process (push branch to this repo to be processed by travis I guess).

**Comment by pzygielo** [comment]
> I suppose things such as https://travis-ci.org/mockito/shipkit/builds/564187877#L444 causes my repeated failures.

Seems so: https://travis-ci.org/mockito/shipkit/builds/564187877#L888

**Comment by pzygielo** [comment]
Or perhaps switching JDK from Oracle to OpenJDK could be considered?
Then no dist would be required as OpenJDK is still available on xenial.

**Comment by epeee** [comment]
@pzygielo yes, I'd rather go for openjdk.

**Comment by pzygielo** [comment]
> @pzygielo yes, I'd rather go for openjdk.

Then please see #837.

**Pull request closed without merging**
